{
  "openapi": "3.0.0",
  "info": {
    "title": "API do TCC databank",
    "description": "Essa API tem como objetivo a manipulação de dados que acontece por trás do projeto TCC DB",
    "termsOfService": "http://localhost:3000/terms",
    "contact": {
      "email": "ganriel201@gmail.com"
    },
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://localhost:3333/",
      "description": "API de testes"
    }
  ],

  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer",
        "bearerFormat": "JWT"
      }
    }
  },

  "paths": {
    "/sessions": {
      "post": {
        "tags": ["Loggin"],
        "summary": "rota de loggin no sistema",
        "description": "É por essa rota que os autores teram acesso ao sistema e poderem cadastrar os trabalhos academicos",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "matricula": { "type": "string" },
                  "password": { "type": "string" },
                  "isOrientador": { "type": "boolean" }
                },
                "example": {
                  "matricula": "401092",
                  "password": "123456",
                  "isOrientador": false
                }
              }
            }
          }
        },
        "responses": {
          "200": { "description": "OK" },
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "item": {
                  "type": "object",
                  "properties": {
                    "token": { "type": "string" },
                    "user": {
                      "type": "object",
                      "propeties": {
                        "name": { "type": "string" },
                        "email": { "type": "string" },
                        "matricula": { "type": "string" }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/universidades": {
      "post": {
        "tags": ["Universidade"],
        "summary": "Cadastro de Instituições de Ensino Superior",
        "description": "Essa rota é responsável por cadastrar as Instituições de Ensino Superior",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nome": { "type": "string" },
                  "cnpj": { "type": "string" }
                },
                "example": {
                  "nome": "Universidade Teste",
                  "cnpj": "Teste CNPJ"
                }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "400": { "description": "Universidade ja está registrada" }
        }
      },
      "get": {
        "tags": ["Universidade"],
        "summary": "Listagem de Instituições de Ensino",
        "description": "Essa rota lista todos as Instituições de Ensino cadastradas no banco de dados",
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "string" },
                      "nome": { "type": "string" },
                      "cnpj": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/universidades/import": {
      "post": {
        "tags": ["Universidade"],
        "summary": "Cadastro de Instituições de Ensino Superior atravez de Upload de arquivo",
        "description": "Através dessa rota você pode cadastrar diversas universidades de uma vez com um arquivo CSV contendo o nome o cnpj da universidade RESPECTIVAMENTE",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": { "type": "object" },
              "properties": {
                "file": { "type": "string", "format": "binary" }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" }
        }
      }
    },
    "/dominios": {
      "post": {
        "tags": ["Universidade"],
        "summary": "Cadastro de dominios",
        "description": "Essa rota é responsável por cadastrar os dominios das universidades",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "dominio": { "type": "string" },
                  "universidade_id": { "type": "string" }
                },
                "example": {
                  "dominio": "ufc.br",
                  "universidade_id": "4ea50475-2cb6-4576-ba55-2a9bffacc8fc"
                }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "400": { "description": "domino ja está registrado!!!" }
        }
      },
      "get": {
        "tags": ["Universidade"],
        "summary": "Listagem de dominios",
        "description": "Essa rota lista todos os dominios cadastrados no banco de dados",
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "dominio": { "type": "string" },
                      "universidade_id": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/campus": {
      "post": {
        "tags": ["Universidade"],
        "summary": "Cadastro de campi",
        "description": "Essa rota é responsável por cadastrar os campi das universidades, insira o nome do campus na propriedade campus, e o id da universidade a qual o campus pertence (consultar na rota de get /universidades)",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nome": { "type": "string" },
                  "universidade_id": { "type": "string" }
                },
                "example": {
                  "nome": "UFC Campus de Sobral",
                  "universidade_id": "8d3888a7-cc28-468e-bcea-23397bdd5f51"
                }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "404": {
            "description": "Universidade não existe!!!\nVocê não pode registrar um campus sem uma universidasde!!!"
          },
          "400": { "description": "esse campus ja foi registrado!!!" }
        }
      }
    },
    "/campus/{universidade_id}": {
      "get": {
        "tags": ["Universidade"],
        "summary": "Listagem de campi",
        "description": "Essa rota lista todos os campi de uma universiade cadastrados no banco de dados",
        "parameters": [
          {
            "name": "universidade_id",
            "in": "path",
            "description": "a rota utiliza o id da universidade pra fazer a busca dos campus pelo banco de dados",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "string" },
                      "nome": { "type": "string" },
                      "universidade_id": { "type": "string" }
                    }
                  }
                }
              }
            }
          },
          "404": { "description": "Universidade não registrada" }
        }
      }
    },
    "/cursos": {
      "post": {
        "tags": ["Universidade"],
        "summary": "Cadastro de cursos de uma universidade",
        "description": "Essa rota é responsável por cadastrar os cursos das universidades, as propriedades turno e modalidade só aceitam tipos específicos. \n Para o turno: \"diurno\", \"noturno\" e \"integral\". \n Para modalidade: \"licenciatura\", \"bacharelado\" e  \"bacharelado e licenciatura\" ",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nome": { "type": "string" },
                  "campus_id": { "type": "string" },
                  "universidade_id": { "type": "string" },
                  "turno": {
                    "type": "\"diurno\" | \"noturno\" | \"integral\""
                  },
                  "modalidade": {
                    "type": "\"licenciatura\" | \"bacharelado\" | \"bacharelado e licenciatura\""
                  }
                },
                "example": {
                  "nome": "Engenharia de Computação",
                  "campus_id": "5002ee8f-d56e-4707-bd7f-1186ba490937",
                  "universidade_id": "8d3888a7-cc28-468e-bcea-23397bdd5f51",
                  "turno": "integral",
                  "modalidade": "bacharelado"
                }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "400": { "description": "curso ja fou registrado!!!" },
          "404": {
            "description": "você pode se deparar com duas mensagens para esses erro, uma informando q a universidade não existe e outra se referindo ao campus"
          }
        }
      }
    },
    "/cursos/{campus_id}": {
      "get": {
        "tags": ["Universidade"],
        "summary": "Listagem de cursos de um campus de uma universidade",
        "description": "Essa rota é responsável por listar todos os cursos de um capmus de uma universidade.",
        "parameters": [
          {
            "name": "campus_id",
            "in": "path",
            "description": "a rota utiliza o id do campus pra fazer a busca dos cursos pelo banco de dados",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "string" },
                      "nome": { "type": "string" },
                      "turno": { "type": "string" },
                      "modalidade": { "type": "string" },
                      "campus_id": { "type": "string" },
                      "universidade_id": { "type": "string" }
                    }
                  }
                }
              }
            }
          },
          "404": { "description": "campus não encontrado" },
          "400": { "description": "entrada invalida" }
        }
      }
    },
    "/areasEstudo": {
      "post": {
        "tags": ["Áreas de Estudo"],
        "summary": "Cadastro de Áreas de Estudo",
        "description": "Essa rota é responsável por cadastrar as Áreas de Estudo, o id é o número identificador listado no CNPQ",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "id": { "type": "string" },
                  "nome": { "type": "string" }
                },
                "example": {
                  "id": "1.00.00.00-3",
                  "nome": "Ciências Exatas e da Terra"
                }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "400": { "description": "Category already exists" }
        }
      },
      "get": {
        "tags": ["Áreas de Estudo"],
        "summary": "Listagem de Áreas de Estudo",
        "description": "Essa rota lista todos as Áreas de Estudo cadastradas no banco de dados",
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "string" },
                      "nome": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/areasEstudo/import": {
      "post": {
        "tags": ["Áreas de Estudo"],
        "summary": "Cadastro de Áreas de Estudo atravez de Upload de arquivo",
        "description": "Através dessa rota você pode cadastrar diversas Áreas de Estudo de uma vez com um arquivo CSV contendo o id e nome da Área de Estudo RESPECTIVAMENTE",
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": { "type": "object" },
              "properties": {
                "file": { "type": "string", "format": "binary" }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" }
        }
      }
    },
    "/autores": {
      "post": {
        "tags": ["Autores"],
        "summary": "Cadastro de Autores",
        "description": "Essa rota é responsável por cadastrar os Autores,\nATENÇÃO: o email tem que ser um email instucional registrado no banco de dados;\nATENÇÃO: o campo data_fim é opcional",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": { "type": "string" },
                  "nome": { "type": "string" },
                  "senha": { "type": "string" },
                  "matricula": { "type": "string" },
                  "curso_id": { "type": "string" },
                  "campus_id": { "type": "string" },
                  "universidade_id": { "type": "string" },
                  "data_inicio": { "type": "string" },
                  "data_fim": { "type": "string" }
                },
                "example": {
                  "email": "exemple@alu.ufc.br",
                  "nome": "Alguem",
                  "senha": "senha de exemplo",
                  "matricula": "123456",
                  "curso_id": "b2617a42-31c0-4b64-8fe5-49d2e1030e1a",
                  "campus_id": "92a8cbdd-b228-49a9-8e7c-1eb7fbc59694",
                  "universidade_id": "58ec464f-2833-480f-b5cf-6068ef21fe86",
                  "data_inicio": "2017-03-23"
                }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "400": { "description": "erro ao cadastrar autor" }
        }
      },
      "get": {
        "tags": ["Autores"],
        "summary": "Listagem de Autores",
        "description": "Essa rota lista todos os Autores cadastradas no banco de dados",
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "string" },
                      "nome": { "type": "string" },
                      "matricula": { "type": "string" },
                      "email": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/autores/createNome": {
      "post": {
        "tags": ["Autores"],
        "summary": "Cadastro de nome em citações bibliográfias",
        "description": "Essa rota é responsável por cadastrar os nomes em citações bibliográficas dos autores, visto que um autor pode ter vários nomes diferentes de citações bibliográficas",
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "nome": { "type": "string" }
                },
                "example": {
                  "nome": "Alguem A."
                }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "401": { "description": "User does not exists!" }
        }
      }
    },
    "/autores/listNomes": {
      "get": {
        "tags": ["Autores"],
        "summary": "Listagem de nomes em citações bibliográfias",
        "description": "Essa rota é responsável por listar os nomes em citações bibliográficas dos autores, visto que um autor pode ter vários nomes diferentes de citações bibliográficas",
        "security": [{ "bearerAuth": [] }],
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "nome": { "type": "string" },
                      "autor_id": { "type": "string" }
                    }
                  }
                }
              }
            }
          }
        }
      }
    },
    "/autores/orientacao": {
      "post": {
        "tags": ["Autores"],
        "summary": "Cadastrar relação entre autor e orientador",
        "description": "Essa rota é responsável por cadastrar as relações entre autores e orientadores",
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "orientador_id": { "type": "string" }
                },
                "example": {
                  "orientador_id": "9cc109c4-a109-42bc-83fe-a8037c02fd52"
                }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "404": { "description": "Autor ou orientador não foi encontrado" },
          "400": { "description": "erro do usuário" }
        }
      }
    },
    "/orientadores": {
      "post": {
        "tags": ["Orientadores"],
        "summary": "Cadastro de Orientadores",
        "description": "Essa rota é responsável por cadastrar os Orientadores, ATENÇÃO: o email tem que ser um email instucional registrado no banco de dados",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": { "type": "string" },
                  "nome": { "type": "string" },
                  "senha": { "type": "string" },
                  "matricula_siape": { "type": "string" }
                },
                "example": {
                  "email": "exemple@alu.ufc.br",
                  "nome": "Alguem",
                  "senha": "senha de exemplo",
                  "matricula_siape": "123456"
                }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "400": { "description": "Orientador Already Exists!!!!" }
        }
      },
      "get": {
        "tags": ["Orientadores"],
        "summary": "Listagem de Orientadores",
        "description": "Essa rota lista todos os Orientadores cadastradas no banco de dados",
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "id": { "type": "string" },
                      "nome": { "type": "string" },
                      "email": { "type": "string" }
                    }
                  }
                }
              }
            }
          },
          "500": { "description": "aconteceu alguma coisa muito errada aqui" }
        }
      }
    },
    "/trabalhos": {
      "post": {
        "tags": ["Trabalhos Acadêmicos"],
        "summary": "Cadastro de Trabalhos Acadêmicos",
        "description": "Essa rota é responsável por cadastrar os Trabalhos Acadêmicos",
        "security": [{ "bearerAuth": [] }],
        "requestBody": {
          "content": {
            "multipart/form-data": {
              "schema": { "type": "object" },
              "properties": {
                "titulo": { "type": "string" },
                "tipo": { "type": "\"TCC\" | \"artigo\" | \"resenha\"" },
                "nivel": {
                  "type": "\"graduação\" | \"mestradro\" | \"doutorado\""
                },
                "arquivo": { "type": "string", "format": "binary" },
                "local_publicacao": { "type": "string" },
                "area_estudo_id": { "type": "string" },
                "orientador_id": { "type": "string" }
              }
            }
          }
        },
        "responses": {
          "201": { "description": "Created" },
          "404": {
            "description": "erro em algum dos campos, autor, orientador ou trabalho não encontrado"
          }
        }
      },
      "get": {
        "tags": ["Trabalhos Acadêmicos"],
        "summary": "Listagem de Trabalhos Acadêmicos",
        "description": "Essa rota lista todos os Trabalhos Acadêmicos cadastradas no banco de dados",
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "type": "array",
                  "items": {
                    "type": "object",
                    "properties": {
                      "titulo": { "type": "string" },
                      "tipo": { "type": "string" },
                      "nivel": { "type": "string" },
                      "local_publicacao": { "type": "string" },
                      "data_publicacao": { "type": "string" },
                      "area_estudo_id": { "type": "string" }
                    }
                  }
                }
              }
            }
          },
          "500": { "description": "um erro muito doido aqui mano" }
        }
      }
    },
    "/trabalhos/{titulo}": {
      "get": {
        "tags": ["Trabalhos Acadêmicos"],
        "summary": "Listagem de Trabalhos Acadêmicos",
        "description": "Essa rota lista todos os Trabalhos Acadêmicos cadastradas no banco de dados",
        "parameters": [
          {
            "name": "titulo",
            "in": "path",
            "description": "a rota utiliza o titulo do trabalho academico pra fazer a busca dos trabalhos pelo banco de dados",
            "required": true
          }
        ],
        "responses": {
          "200": {
            "description": "success",
            "content": {
              "application/json": {
                "schema": {
                  "items": {
                    "type": "object",
                    "properties": {
                      "arquivo": { "type": "string", "format": "binary" }
                    }
                  }
                }
              }
            }
          },
          "404": { "description": "trabalho não encontrado" }
        }
      }
    }
  }
}
